apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "kibana:5601"
